package com.codepilot1c.core.edt.metadata;

/**
 * Error codes for metadata creation/edit operations.
 */
public enum MetadataOperationCode {
    PROJECT_NOT_FOUND,
    PROJECT_NOT_READY,
    INVALID_METADATA_KIND,
    INVALID_METADATA_NAME,
    METADATA_PARENT_NOT_FOUND,
    METADATA_ALREADY_EXISTS,
    KNOWLEDGE_REQUIRED,
    INVALID_VALIDATION_TOKEN,
    EDT_SERVICE_UNAVAILABLE,
    EDT_TRANSACTION_FAILED,
    METADATA_NOT_FOUND,
    INVALID_PROPERTY_VALUE,
    INVALID_METADATA_CHANGE,
    METADATA_DELETE_CONFLICT,
    INVALID_FORM_USAGE,
    FORM_ALREADY_EXISTS,
    FORM_MATERIALIZATION_TIMEOUT
}
