/*
 * Copyright (c) 2024 Example
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, version 3.
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package com.codepilot1c.core.gsd;

import java.io.IOException;
import java.io.Reader;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.channels.OverlappingFileLockException;
import java.nio.charset.StandardCharsets;
import java.nio.file.AccessDeniedException;
import java.nio.file.AtomicMoveNotSupportedException;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.OpenOption;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.locks.ReentrantLock;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;

/**
 * Persists {@link GsdState} under {@code <project>/.codepilot1c/gsd}.
 *
 * <p>{@code state.json} is the single source of truth. {@code STATE.md} and {@code PLAN.md}
 * are deterministic projections regenerated by this store from JSON and carry no
 * independent state. Writes are atomic: a temp file is written in the GSD directory,
 * {@link FileChannel#force(boolean) force}d to disk, and moved into place with
 * {@link StandardCopyOption#ATOMIC_MOVE}. The only fallback is for filesystems that do not
 * support atomic moves ({@link AtomicMoveNotSupportedException}), in which case a
 * non-atomic {@link StandardCopyOption#REPLACE_EXISTING} move is used. After the rename,
 * the GSD directory is best-effort {@link FileChannel#force force}d so the rename is
 * durable; filesystems without directory fsync are documented below and tolerated.</p>
 *
 * <p>Optimistic concurrency is enforced via the cycle/generation/revision
 * {@link GsdConcurrencyToken} <b>under a cross-process
 * {@link FileLock}</b> on {@code .codepilot1c/gsd/state.lock}: {@link #save(GsdState)}
 * acquires the lock, checks that {@code state.revision()} equals the revision on disk,
 * backs up the previous {@code state.json} to {@code state.json.bak}, persists the new
 * state with {@code revision + 1}, regenerates projections, and releases the lock — all
 * as one critical section, so two writers cannot both pass the CAS. Within a single
 * JVM the OS {@link FileLock} is owned by the process; a second channel on the same
 * lock file throws {@link OverlappingFileLockException} instead of blocking, so the
 * store additionally serializes threads with a per-real-path {@link
 * java.util.concurrent.locks.ReentrantLock}. Across processes, only the OS file lock
 * serializes writers. A revision mismatch raises {@link GsdStaleRevisionException}
 * (fail-closed) so the caller reloads and retries. Backup recovery advances generation,
 * and a new delivery cycle changes cycle id, so revision reuse cannot cause ABA.</p>
 *
 * <p>Backup/recovery: on {@link #load()}, a primary {@code state.json} that is
 * {@link GsdCorruptException corrupt} is recovered from {@code state.json.bak} (the
 * corrupt file is quarantined to {@code state.json.corrupt} for forensics; quarantine
 * failures propagate). A <em>missing</em> primary with a <em>valid</em> backup is also
 * recovered. Ordinary access/I/O failures (e.g. {@link AccessDeniedException}) propagate
 * verbatim — they are never treated as corruption and never trigger silent backup
 * recovery. If the primary is corrupt and the backup is missing or corrupt, the store
 * fails closed with {@link GsdCorruptException}. A genuinely fresh project (no
 * {@code state.json}, no {@code .bak}) yields a fresh {@link GsdState#fresh()} without
 * writing a primary state file; missing Markdown projections may still be generated.</p>
 *
 * <p>The {@link GsdGuard} invariants are validated before any write, so a state that would
 * close work on {@link GsdProvenance#INFERRED}-only evidence can never reach disk.</p>
 *
 * <p>Filesystem confinement: the GSD directory is resolved under the supplied project
 * root and must stay inside it after symlink resolution; escapes are rejected. This is
 * pure core, provider-neutral, with no UI dependencies.</p>
 *
 * <h2>Directory fsync limitation</h2>
 * <p>{@link FileChannel#force} on a directory is a no-op on many platforms (notably
 * Windows and some macOS configurations). On such filesystems the rename durability
 * depends on the {@link StandardCopyOption#ATOMIC_MOVE} guarantee alone; if the OS
 * crashes before the directory entry is flushed, the previous {@code state.json} may
 * still be visible. The backup file ({@code state.json.bak}) plus the recovery-on-load
 * path mitigate this: the worst case is reverting to the prior revision, never to
 * corruption. Platform-specific block-device and POSIX {@code fsync(dir)} semantics are
 * not queried at runtime to keep the store portable.</p>
 */
public final class GsdStateStore {

    /** Directory under the project root where GSD state lives. */
    public static final String GSD_DIR_NAME = ".codepilot1c/gsd"; //$NON-NLS-1$
    /** Primary state file (source of truth). */
    public static final String STATE_JSON = "state.json"; //$NON-NLS-1$
    /** Backup of the previous good state. */
    public static final String STATE_BAK = "state.json.bak"; //$NON-NLS-1$
    /** Forensic copy of a corrupt state.json. */
    public static final String STATE_CORRUPT = "state.json.corrupt"; //$NON-NLS-1$
    /** Cross-process inter-process lock file. */
    public static final String STATE_LOCK = "state.lock"; //$NON-NLS-1$

    private static final String TEMP_PREFIX = ".state-"; //$NON-NLS-1$
    private static final String TEMP_SUFFIX = ".tmp"; //$NON-NLS-1$

    private static final OpenOption[] WRITE_OPTS = {
            StandardOpenOption.WRITE, StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING
    };

    /**
     * Per-real-path JVM mutexes. {@link FileLock} is held by the JVM as a whole: a second
     * {@link FileChannel} on the same path in the same process does <em>not</em> block on
     * {@link FileChannel#lock()} — it throws {@link OverlappingFileLockException} because
     * the JVM already owns the lock region. To serialize threads within a single JVM
     * while still using an OS {@link FileLock} to serialize across processes, each store
     * first acquires a {@link ReentrantLock} keyed by the real path of the lock file, then
     * acquires the OS file lock. The map is static so all store instances in this JVM
     * share the same per-path mutex.
     */
    private static final ConcurrentHashMap<Path, ReentrantLock> JVM_LOCKS =
            new ConcurrentHashMap<>();

    private final Path projectRoot;
    private final Path gsdDir;
    private final Path statePath;
    private final Path bakPath;
    private final Path corruptPath;
    private final Path lockPath;
    private final Gson gson;

    /**
     * Creates a store confined to {@code <projectRoot>/.codepilot1c/gsd}.
     *
     * @param projectRoot the project root (must not be {@code null})
     * @throws IOException if the project root is invalid or confinement cannot be established
     */
    public GsdStateStore(Path projectRoot) throws IOException {
        this.projectRoot = normalizeRoot(projectRoot);
        Path candidate = this.projectRoot.resolve(GSD_DIR_NAME).toAbsolutePath().normalize();
        if (!candidate.startsWith(this.projectRoot)) {
            throw new AccessDeniedException(candidate.toString(), null,
                    "GSD path escapes project root"); //$NON-NLS-1$
        }
        this.gsdDir = candidate;
        this.statePath = gsdDir.resolve(STATE_JSON);
        this.bakPath = gsdDir.resolve(STATE_BAK);
        this.corruptPath = gsdDir.resolve(STATE_CORRUPT);
        this.lockPath = gsdDir.resolve(STATE_LOCK);
        this.gson = buildGson();
    }

    /**
     * Convenience constructor accepting a string project root path.
     *
     * @param projectRootPath the project root path
     * @throws IOException if the path is invalid or confinement cannot be established
     */
    public GsdStateStore(String projectRootPath) throws IOException {
        this(parseRoot(projectRootPath));
    }

    /**
     * @return the confined GSD directory (created lazily on write)
     */
    public Path getGsdDirectory() {
        return gsdDir;
    }

    /**
     * @return the project root this store is confined to
     */
    public Path getProjectRoot() {
        return projectRoot;
    }

    /**
     * Loads the current state under the cross-process lock. Returns
     * {@link GsdState#fresh()} for a project with no GSD state yet (without writing).
     * Recovers from {@code state.json.bak} if {@code state.json} is corrupt or missing,
     * restoring the recovered state to {@code state.json} and regenerating projections.
     * Fails closed with {@link GsdCorruptException} if the primary is corrupt and the
     * backup is missing or corrupt. Ordinary I/O failures propagate as
     * {@link IOException}.
     *
     * @return the loaded (or fresh) state, never {@code null}
     * @throws IOException            if the state is corrupt and unrecoverable, or I/O fails
     */
    public GsdState load() throws IOException {
        ensureConfined();
        return withLock(() -> {
            ReadOutcome outcome = readOutcome(statePath, bakPath);
            if (outcome.state == null) {
                // Fresh project: nothing on disk.
                GsdState fresh = GsdState.fresh();
                regenerateProjectionsIfMissing(fresh);
                return fresh;
            }
            if (outcome.recovered) {
                if (outcome.primaryWasCorrupt) {
                    quarantineCorruptPrimary(); // propagates IOException on failure
                }
                GsdState recovered = outcome.state.recovered();
                atomicWrite(statePath, toBytes(recovered));
                // Advance the recovery fence in both copies. Repeated recovery without
                // an intervening save must still produce a new generation.
                atomicWrite(bakPath, toBytes(recovered));
                writeProjectionsUnlocked(recovered);
                return recovered;
            } else if (outcome.migrated) {
                // Preserve the original v1 payload as the backup, then publish v2.
                Files.copy(statePath, bakPath, StandardCopyOption.REPLACE_EXISTING);
                atomicWrite(statePath, toBytes(outcome.state));
                writeProjectionsUnlocked(outcome.state);
            } else {
                regenerateProjectionsIfMissing(outcome.state);
            }
            return outcome.state;
        });
    }

    /**
     * Reads the current state without any filesystem writes.
     *
     * <p>Unlike {@link #load()}, this method never creates directories, never acquires
     * the cross-process lock, never regenerates projections, never quarantines or
     * publishes a backup, and never recovers from {@code state.json.bak}. Because
     * writes are atomic ({@link StandardCopyOption#ATOMIC_MOVE}), a concurrent
     * reader is safe: it either sees the fully-written previous state or the new one,
     * never a half-written file.</p>
     *
     * <p>Behavior:</p>
     * <ul>
     *   <li>Primary {@code state.json} exists and parses correctly → returns the parsed state.</li>
     *   <li>Primary {@code state.json} exists but is corrupt → throws
     *       {@link GsdCorruptException} (caller surfaces the error in the UI).</li>
     *   <li>Primary {@code state.json} does not exist → returns {@link GsdState#fresh()}.</li>
     *   <li>I/O failure reading the primary → propagates as {@link IOException}.</li>
     * </ul>
     *
     * <p>Confinement is enforced before reading: a pre-existing symlink (e.g.
     * {@code .codepilot1c} pointing outside the project root) is rejected with
     * {@link AccessDeniedException}, preventing reads of another project's state.
     * This check is purely read-only — no directories or files are created.</p>
     *
     * <p>This method is designed for read-only UI consumers (e.g. status panels)
     * that must never mutate the project directory.</p>
     *
     * @return the loaded state, or {@link GsdState#fresh()} when no primary exists; never {@code null}
     * @throws GsdCorruptException  if the primary exists but is corrupt
     * @throws AccessDeniedException if the GSD directory escapes the project root via symlink
     * @throws IOException          on I/O failure reading the primary
     */
    public GsdState loadReadOnly() throws IOException {
        ensureConfined();
        if (!Files.exists(statePath)) {
            return GsdState.fresh();
        }
        return parseState(statePath).state;
    }

    /**
     * Persists the state atomically under the cross-process lock. Enforces
     * {@link GsdGuard} and optimistic revision before writing. Backs up the previous
     * {@code state.json} to {@code state.json.bak}, writes the new state with
     * {@code revision + 1}, and attempts to regenerate {@code STATE.md}/{@code PLAN.md}.
     * Use {@link #commit(GsdState)} when projection warnings must be observed.
     *
     * @param state the state to persist; its full {@link GsdState#concurrencyToken()} is checked
     * @return the newly persisted state with incremented revision (never {@code null})
     * @throws GsdGuardException          if the state violates invariants
     * @throws GsdStaleRevisionException if {@code state.revision()} does not match disk
     * @throws IOException               on I/O failure or unrecoverable corruption (fail-closed)
     */
    public GsdState save(GsdState state) throws IOException {
        return commit(state).state();
    }

    /**
     * Atomically commits authoritative state and reports non-authoritative projection
     * failures as warnings. If this method returns, {@code committed()} is true.
     * Failures before the state rename still throw and commit nothing.
     *
     * @param state desired state carrying the expected concurrency token
     * @return committed state plus projection warnings
     * @throws IOException on authoritative persistence failure
     */
    public GsdCommitOutcome commit(GsdState state) throws IOException {
        GsdState validated = Objects.requireNonNull(state, "state"); //$NON-NLS-1$
        GsdGuard.validate(validated); // fail-closed before any write / before the lock

        return withLock(() -> {
            validateBeforeSave(validated);
            GsdState next = validated.withRevision(validated.revision() + 1L);
            commitAuthoritative(next);
            return projectionOutcome(next);
        });
    }

    /** Compatibility alias emphasizing that projection warnings are returned. */
    public GsdCommitOutcome saveWithOutcome(GsdState state) throws IOException {
        return commit(state);
    }

    /**
     * Commits a CLOSED-to-DISCOVERY cycle replacement against the old token. The new
     * cycle starts at revision zero, so the explicit expected token is required.
     */
    public GsdCommitOutcome commitNewCycle(GsdConcurrencyToken expectedToken,
            GsdState newCycle) throws IOException {
        Objects.requireNonNull(expectedToken, "expectedToken"); //$NON-NLS-1$
        GsdState validated = Objects.requireNonNull(newCycle, "newCycle"); //$NON-NLS-1$
        GsdGuard.validate(validated);
        if (validated.phase() != GsdPhase.DISCOVERY
                || validated.revision() != GsdState.INITIAL_REVISION) {
            throw new IllegalArgumentException("new cycle must start in DISCOVERY at revision 0"); //$NON-NLS-1$
        }
        return withLock(() -> {
            ReadOutcome outcome = readOutcome(statePath, bakPath);
            if (outcome.state == null || outcome.recovered || outcome.migrated) {
                throw new GsdCorruptException(
                        "cannot replace cycle until primary state is loaded and current"); //$NON-NLS-1$
            }
            if (!expectedToken.equals(outcome.state.concurrencyToken())) {
                throw new GsdStaleTokenException(expectedToken, outcome.state.concurrencyToken());
            }
            if (outcome.state.phase() != GsdPhase.CLOSED) {
                throw new IllegalStateException("new cycle requires current phase CLOSED"); //$NON-NLS-1$
            }
            if (expectedToken.cycleId().equals(validated.cycleId())) {
                throw new IllegalArgumentException("new cycleId must differ from the closed cycle"); //$NON-NLS-1$
            }
            commitAuthoritative(validated);
            return projectionOutcome(validated);
        });
    }

    private void commitAuthoritative(GsdState next) throws IOException {
        if (Files.exists(statePath)) {
            Files.copy(statePath, bakPath, StandardCopyOption.REPLACE_EXISTING);
        }
        atomicWrite(statePath, toBytes(next));
    }

    private GsdCommitOutcome projectionOutcome(GsdState next) {
        List<String> warnings = new ArrayList<>();
        try {
            writeProjectionsUnlocked(next);
        } catch (IOException | RuntimeException e) {
            warnings.add("state committed but projections were not fully regenerated: " //$NON-NLS-1$
                    + e.getClass().getSimpleName() + ": " + e.getMessage()); //$NON-NLS-1$
        }
        return new GsdCommitOutcome(next, true, warnings);
    }

    /**
     * Pre-save validation under lock. Returns the state found on disk (for revision
     * comparison and stale-revision checks). Handles three cases:
     * <ul>
     *   <li>Fresh project ({@code state==null}): returns {@code null} to signal
     *       no prior state exists.</li>
     *   <li>Recovery needed ({@code recovered==true}): fails closed with
     *       {@link GsdCorruptException} because only a validated primary may be backed up.</li>
     *   <li>Normal state on disk: returns the valid state for CAS checking.</li>
     * </ul>
     */
    private void validateBeforeSave(GsdState validated) throws IOException {
        ReadOutcome outcome = readOutcome(statePath, bakPath);

        // Fresh project: no existing state on disk, nothing to back up.
        if (outcome.state == null) {
            if (validated.revision() != GsdState.INITIAL_REVISION) {
                throw new GsdStaleRevisionException(
                        validated.revision(), GsdState.INITIAL_REVISION);
            }
            return;
        }

        // If the store had to recover (primary was corrupt or missing),
        // reject the save: only a validated primary may be backed up. A recovered state
        // is transient — the caller must reload via load() to obtain a clean snapshot
        // before attempting another save.
        if (outcome.recovered || outcome.migrated) {
            throw new GsdCorruptException(
                    "GSD primary requires recovery or migration; save rejected until load() completes"); //$NON-NLS-1$
        }

        // Compare the complete identity; revision-only comparison permits ABA after
        // recovery or cycle replacement.
        if (!validated.concurrencyToken().equals(outcome.state.concurrencyToken())) {
            throw new GsdStaleTokenException(
                    validated.concurrencyToken(), outcome.state.concurrencyToken());
        }
    }

    /**
     * Regenerates the {@code STATE.md} and {@code PLAN.md} projections from the given
     * state under the cross-process lock, without changing {@code state.json}. Useful
     * after a fresh checkout or manual edits.
     *
     * @param state the state to project
     * @throws IOException on I/O failure
     */
    public void writeProjections(GsdState state) throws IOException {
        Objects.requireNonNull(state, "state"); //$NON-NLS-1$
        withLock(() -> {
            ensureConfined();
            Files.createDirectories(gsdDir);
            writeProjectionsUnlocked(state);
            return null;
        });
    }

    // ---- Internals -------------------------------------------------------

    private void writeProjectionsUnlocked(GsdState state) throws IOException {
        atomicWriteText(gsdDir.resolve(GsdProjections.STATE_FILE), GsdProjections.toStateMd(state));
        atomicWriteText(gsdDir.resolve(GsdProjections.PLAN_FILE), GsdProjections.toPlanMd(state));
    }

    /**
     * Executes {@code action} while holding an exclusive cross-process {@link FileLock}
     * on {@code state.lock}. The lock file is created on demand. Because {@link FileLock}
     * is owned by the JVM (not the channel), a second channel in the same JVM throws
     * {@link OverlappingFileLockException}; to serialize threads within the process we
     * first take a {@link ReentrantLock} keyed by the lock file's real path, then take the
     * OS file lock. Across processes, only the OS {@link FileLock} serializes writers.
     */
    private <T> T withLock(IoAction<T> action) throws IOException {
        ensureConfined();
        Files.createDirectories(gsdDir);
        verifyRealConfined();
        Path realLockPath = gsdDir.toRealPath().resolve(STATE_LOCK);
        ReentrantLock jvmLock = JVM_LOCKS.computeIfAbsent(realLockPath, k -> new ReentrantLock());
        jvmLock.lock();
        try {
            FileChannel channel = FileChannel.open(lockPath,
                    StandardOpenOption.WRITE, StandardOpenOption.CREATE);
            try {
                FileLock lock;
                try {
                    lock = channel.lock();
                } catch (OverlappingFileLockException e) {
                    // Should not happen: the JVM lock guarantees a single in-process holder.
                    throw new IOException("GSD lock is already held in this JVM", e); //$NON-NLS-1$
                }
                try {
                    return action.run();
                } finally {
                    releaseQuietly(lock);
                }
            } finally {
                closeQuietly(channel);
            }
        } finally {
            jvmLock.unlock();
        }
    }

    @FunctionalInterface
    private interface IoAction<T> {
        T run() throws IOException;
    }

    private void regenerateProjectionsIfMissing(GsdState state) throws IOException {
        Path stateMd = gsdDir.resolve(GsdProjections.STATE_FILE);
        Path planMd = gsdDir.resolve(GsdProjections.PLAN_FILE);
        if (!Files.exists(stateMd) || !Files.exists(planMd)) {
            Files.createDirectories(gsdDir);
            writeProjectionsUnlocked(state);
        }
    }

    /**
     * Reads the primary state file, falling back to the backup if the primary is
     * {@link GsdCorruptException corrupt} (parse/schema error only) or missing while a
     * valid backup exists. Ordinary access/I/O failures propagate verbatim.
     */
    private ReadOutcome readOutcome(Path primary, Path backup) throws IOException {
        boolean primaryCorrupt = false;
        if (Files.exists(primary)) {
            try {
                ParsedState parsed = parseState(primary);
                return new ReadOutcome(parsed.state, false, false, parsed.migrated);
            } catch (GsdCorruptException e) {
                primaryCorrupt = true;
            }
        }
        if (Files.exists(backup)) {
            try {
                ParsedState parsed = parseState(backup);
                return new ReadOutcome(parsed.state, primaryCorrupt, true, parsed.migrated);
            } catch (GsdCorruptException e) {
                // backup also corrupt
                if (primaryCorrupt) {
                    throw new GsdCorruptException("GSD " + STATE_JSON //$NON-NLS-1$
                            + " and " + STATE_BAK + " are both corrupt", e); //$NON-NLS-1$ //$NON-NLS-2$
                }
                // primary missing, backup corrupt -> fail closed on the backup.
                throw new GsdCorruptException("GSD " + STATE_BAK + " is corrupt and " //$NON-NLS-1$ //$NON-NLS-2$
                        + STATE_JSON + " is missing: " + e.getMessage(), e); //$NON-NLS-1$ //$NON-NLS-2$
            }
        }
        if (primaryCorrupt) {
            throw new GsdCorruptException("GSD " + STATE_JSON + " is corrupt and " //$NON-NLS-1$ //$NON-NLS-2$
                    + STATE_BAK + " is missing"); //$NON-NLS-1$
        }
        // primary simply missing and no backup to recover from (fresh project).
        return new ReadOutcome(null, false, false, false);
    }

    /**
     * Moves the corrupt primary {@code state.json} to {@code state.json.corrupt} for
     * forensic analysis. Fails closed by propagating any {@link IOException}; the
     * original recovery is abandoned so a corrupt file is never silently lost.
     */
    private void quarantineCorruptPrimary() throws IOException {
        if (!Files.exists(statePath)) {
            return;
        }
        try {
            Files.move(statePath, corruptPath, StandardCopyOption.REPLACE_EXISTING,
                    StandardCopyOption.ATOMIC_MOVE);
        } catch (AtomicMoveNotSupportedException e) {
            Files.move(statePath, corruptPath, StandardCopyOption.REPLACE_EXISTING);
        }
        // If a previous forensic copy lingered, only one .corrupt is kept (REPLACE_EXISTING).
    }

    private byte[] toBytes(GsdState state) {
        return gson.toJson(state).getBytes(StandardCharsets.UTF_8);
    }

    /**
     * Parses {@code path} as a {@link GsdState}. Raises {@link GsdCorruptException} for
     * unparseable JSON, a JSON {@code null} document, an empty document, a
     * unsupported historical schema, or a {@link GsdGuard} invariant violation. Schema v1
     * is migrated explicitly; a future schema raises {@link GsdUnsupportedSchemaException}.
     * All other
     * {@link IOException}s propagate.
     */
    private ParsedState parseState(Path path) throws IOException {
        long size;
        try {
            size = Files.size(path);
        } catch (IOException e) {
            throw e; // access failure propagates verbatim
        }
        if (size == 0) {
            throw new GsdCorruptException("empty GSD state file: " + path); //$NON-NLS-1$
        }
        JsonObject document;
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            JsonElement parsed = JsonParser.parseReader(reader);
            if (parsed == null || parsed.isJsonNull()) {
                throw new GsdCorruptException("GSD state file is JSON null: " + path); //$NON-NLS-1$
            }
            if (!parsed.isJsonObject()) {
                throw new GsdCorruptException("GSD state file is not a JSON object: " + path); //$NON-NLS-1$
            }
            document = parsed.getAsJsonObject();
        } catch (JsonSyntaxException e) {
            throw new GsdCorruptException("invalid JSON in " + path + ": " + e.getMessage(), e); //$NON-NLS-1$ //$NON-NLS-2$
        }
        JsonElement schemaElement = document.get("schemaVersion"); //$NON-NLS-1$
        if (schemaElement == null || !schemaElement.isJsonPrimitive()
                || !schemaElement.getAsJsonPrimitive().isNumber()) {
            throw new GsdCorruptException("missing or invalid GSD schemaVersion in " + path); //$NON-NLS-1$
        }
        int schemaVersion;
        try {
            schemaVersion = Integer.parseInt(schemaElement.getAsString());
        } catch (RuntimeException e) {
            throw new GsdCorruptException("invalid GSD schemaVersion in " + path, e); //$NON-NLS-1$
        }
        if (schemaVersion > GsdState.CURRENT_SCHEMA_VERSION) {
            // A future schema is not corruption and must never silently fall back to
            // an older backup.
            throw new GsdUnsupportedSchemaException(schemaVersion);
        }

        final GsdState state;
        final boolean migrated;
        try {
            if (schemaVersion == GsdState.LEGACY_SCHEMA_VERSION) {
                LegacyStateV1 legacy = gson.fromJson(document, LegacyStateV1.class);
                state = GsdState.migratedFromV1(legacy.revision, legacy.phase, legacy.goal,
                        legacy.decisions, legacy.tasks, legacy.waves, legacy.evidence,
                        legacy.sessionPointer);
                migrated = true;
            } else if (schemaVersion == GsdState.CURRENT_SCHEMA_VERSION) {
                state = gson.fromJson(document, GsdState.class);
                migrated = false;
            } else {
                throw new GsdCorruptException("unsupported historical GSD schemaVersion " //$NON-NLS-1$
                        + schemaVersion + " in " + path); //$NON-NLS-1$
            }
        } catch (RuntimeException e) {
            throw new GsdCorruptException("invalid GSD state in " + path + ": " //$NON-NLS-1$ //$NON-NLS-2$
                    + e.getMessage(), e);
        }
        // Guard validation: a deserialized state that violates invariants is treated as
        // corruption so that backup-recovery paths never republish invalid state.
        try {
            GsdGuard.validate(state);
        } catch (GsdGuardException e) {
            throw new GsdCorruptException("GSD state in " + path + " fails guard validation: " //$NON-NLS-1$ //$NON-NLS-2$
                    + e.getMessage(), e);
        }
        return new ParsedState(state, migrated);
    }

    /**
     * Writes {@code bytes} to {@code target} via a temp file in the same directory,
     * {@link FileChannel#force force}d to disk, then moved into place atomically. The
     * full payload is written in a loop so short writes cannot leave a partial file.
     * Falls back to a non-atomic replace only on {@link AtomicMoveNotSupportedException}.
     * The parent directory is best-effort fsynced after the move.
     */
    private void atomicWrite(Path target, byte[] bytes) throws IOException {
        Files.createDirectories(target.getParent());
        Path temp = Files.createTempFile(target.getParent(), TEMP_PREFIX, TEMP_SUFFIX);
        boolean moved = false;
        try {
            writeAll(temp, bytes);
            try {
                Files.move(temp, target, StandardCopyOption.ATOMIC_MOVE,
                        StandardCopyOption.REPLACE_EXISTING);
            } catch (AtomicMoveNotSupportedException e) {
                Files.move(temp, target, StandardCopyOption.REPLACE_EXISTING);
            }
            moved = true;
            syncDirectory(target.getParent());
        } catch (IOException e) {
            throw e;
        } finally {
            if (!moved) {
                deleteQuietly(temp);
            }
        }
    }

    /**
     * Writes the entire {@code buffer} to {@code path} via a {@link FileChannel}, looping
     * until all bytes are written, then {@link FileChannel#force(boolean) force}d (incl.
     * metadata) so the temp file is durable before the rename.
     */
    private static void writeAll(Path path, byte[] bytes) throws IOException {
        ByteBuffer buffer = ByteBuffer.wrap(bytes);
        try (FileChannel channel = FileChannel.open(path, WRITE_OPTS)) {
            while (buffer.hasRemaining()) {
                int written = channel.write(buffer);
                if (written < 0) {
                    throw new IOException("unexpected end of write channel for " + path); //$NON-NLS-1$
                }
            }
            channel.force(true);
        }
    }

    /**
     * Best-effort durability of the directory entry for the renamed file. Opening a
     * directory for write and calling {@link FileChannel#force} is supported on POSIX
     * filesystems; on Windows and some macOS setups it is a no-op or unsupported and
     * is tolerated (documented at class level).
     */
    private static void syncDirectory(Path dir) {
        try (FileChannel channel = FileChannel.open(dir, StandardOpenOption.READ)) {
            try {
                channel.force(true);
            } catch (IOException ignored) {
                // fsync unsupported on this directory; tolerated.
            }
        } catch (IOException | UnsupportedOperationException ignored) {
            // Directory fsync not supported here; durability relies on the atomic move.
        }
    }

    private void atomicWriteText(Path target, String text) throws IOException {
        atomicWrite(target, text.getBytes(StandardCharsets.UTF_8));
    }

    private static void deleteQuietly(Path path) {
        try {
            Files.deleteIfExists(path);
        } catch (IOException ignored) {
            // best-effort cleanup of temp
        }
    }

    private static void closeQuietly(FileChannel channel) {
        try {
            channel.close();
        } catch (IOException ignored) {
            // closing the lock channel also releases the lock
        }
    }

    private static void releaseQuietly(FileLock lock) {
        try {
            lock.release();
        } catch (IOException ignored) {
            // best-effort release; channel close will also release
        }
    }

    private static Path normalizeRoot(Path root) throws IOException {
        if (root == null) {
            throw new IOException("project root must not be null"); //$NON-NLS-1$
        }
        try {
            return root.toAbsolutePath().normalize();
        } catch (InvalidPathException e) {
            throw new IOException("invalid project root: " + root, e); //$NON-NLS-1$
        }
    }

    private static Path parseRoot(String path) throws IOException {
        if (path == null || path.isBlank()) {
            throw new IOException("project root path must not be blank"); //$NON-NLS-1$
        }
        try {
            return Path.of(path);
        } catch (InvalidPathException e) {
            throw new IOException("invalid project root path: " + path, e); //$NON-NLS-1$
        }
    }

    /**
     * Verifies the GSD directory stays inside the project root after symlink resolution,
     * resolving through the longest existing ancestor so a pre-existing symlink (e.g.
     * {@code .codepilot1c} pointing outside the project) is rejected before any directory
     * is created. Called before reads and writes.
     */
    private void ensureConfined() throws IOException {
        Path realRoot;
        try {
            realRoot = projectRoot.toRealPath();
        } catch (IOException e) {
            throw new IOException("project root does not exist or is inaccessible: " //$NON-NLS-1$
                    + projectRoot, e);
        }
        Path existingAncestor = longestExistingAncestor(gsdDir);
        if (existingAncestor == null) {
            return; // nothing exists yet; lexical check already passed, creation is safe
        }
        Path realAncestor = existingAncestor.toRealPath();
        if (existingAncestor.getNameCount() < gsdDir.getNameCount()) {
            Path relative = gsdDir.subpath(existingAncestor.getNameCount(), gsdDir.getNameCount());
            Path realGsd = realAncestor.resolve(relative);
            if (!realGsd.startsWith(realRoot)) {
                throw new AccessDeniedException(gsdDir.toString(), null,
                        "GSD directory resolves outside the project root"); //$NON-NLS-1$
            }
        } else if (!realAncestor.startsWith(realRoot)) {
            throw new AccessDeniedException(gsdDir.toString(), null,
                    "GSD directory resolves outside the project root"); //$NON-NLS-1$
        }
    }

    /** Re-checks confinement after directory creation to catch symlink swaps. */
    private void verifyRealConfined() throws IOException {
        Path realRoot = projectRoot.toRealPath();
        Path realGsd = gsdDir.toRealPath();
        if (!realGsd.startsWith(realRoot)) {
            throw new AccessDeniedException(gsdDir.toString(), null,
                    "GSD directory resolves outside the project root"); //$NON-NLS-1$
        }
    }

    private static Path longestExistingAncestor(Path path) {
        Path cur = path;
        while (cur != null && !Files.exists(cur)) {
            cur = cur.getParent();
        }
        return cur;
    }

    private static Gson buildGson() {
        return new GsonBuilder()
                .setPrettyPrinting()
                .disableHtmlEscaping()
                .registerTypeAdapter(Instant.class, new InstantAdapter().nullSafe())
                .registerTypeAdapter(GsdPhase.class, new EnumStrictAdapter<>(GsdPhase.class, "phase"))
                .registerTypeAdapter(GsdTaskStatus.class, new EnumStrictAdapter<>(GsdTaskStatus.class, "task status"))
                .registerTypeAdapter(GsdProvenance.class, new EnumStrictAdapter<>(GsdProvenance.class, "provenance"))
                .registerTypeAdapter(GsdExecutionKind.class, new EnumStrictAdapter<>(GsdExecutionKind.class, "execution kind"))
                .registerTypeAdapter(GsdAcceptanceStatus.class, new EnumStrictAdapter<>(GsdAcceptanceStatus.class, "acceptance status"))
                .registerTypeAdapter(GsdShipmentStatus.class, new EnumStrictAdapter<>(GsdShipmentStatus.class, "shipment status"))
                .create();
    }

    /** Outcome of a read attempt, tracking whether recovery from backup occurred. */
    private static final class ReadOutcome {
        final GsdState state;
        final boolean primaryWasCorrupt;
        final boolean recovered;
        final boolean migrated;

        ReadOutcome(GsdState state, boolean primaryWasCorrupt, boolean recovered, boolean migrated) {
            this.state = state;
            this.primaryWasCorrupt = primaryWasCorrupt;
            this.recovered = recovered;
            this.migrated = migrated;
        }
    }

    private static final class ParsedState {
        final GsdState state;
        final boolean migrated;

        ParsedState(GsdState state, boolean migrated) {
            this.state = state;
            this.migrated = migrated;
        }
    }

    /** Exact schema-v1 shape used only by the explicit one-step migrator. */
    private static final class LegacyStateV1 {
        long revision;
        GsdPhase phase;
        String goal;
        List<GsdDecision> decisions;
        List<GsdTask> tasks;
        List<GsdWave> waves;
        List<GsdEvidence> evidence;
        GsdSessionPointer sessionPointer;
    }

    /**
     * Strict {@link TypeAdapter} for Java enums that treats any unrecognized JSON string
     * as corruption rather than silently falling back to {@code null} or a default value.
     *
     * @param <E> the enum type
     */
    private static final class EnumStrictAdapter<E extends Enum<E>> extends TypeAdapter<E> {
        private final Class<E> enumType;
        private final String fieldName; // for error messages

        EnumStrictAdapter(Class<E> enumType, String fieldName) {
            this.enumType = enumType;
            this.fieldName = fieldName;
        }

        @Override
        public void write(JsonWriter out, E value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(value.name());
            }
        }

        @Override
        public E read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                throw new GsdCorruptException(
                        "Null " + fieldName + " value in JSON — possible data corruption"); //$NON-NLS-1$ //$NON-NLS-2$
            }
            String name = in.nextString();
            try {
                return Enum.valueOf(enumType, name);
            } catch (IllegalArgumentException e) {
                throw new GsdCorruptException("Unknown " + fieldName + " value '" + name
                        + "' in JSON — possible data corruption", e);
            }
        }
    }

    /** ISO-8601 adapter for {@link Instant} so JSON is human-readable and deterministic. */
    private static final class InstantAdapter extends TypeAdapter<Instant> {
        @Override
        public void write(JsonWriter out, Instant value) throws IOException {
            out.value(value.toString());
        }

        @Override
        public Instant read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            return Instant.parse(in.nextString());
        }
    }
}
