/*
 * Copyright (c) 2024 Example
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, version 3.
 * SPDX-License-Identifier: AGPL-3.0-only
 */
package com.codepilot1c.core.gsd;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.ByteBuffer;
import java.nio.channels.FileChannel;
import java.nio.channels.FileLock;
import java.nio.channels.OverlappingFileLockException;
import java.nio.channels.SeekableByteChannel;
import java.nio.charset.StandardCharsets;
import java.nio.file.AccessDeniedException;
import java.nio.file.Files;
import java.nio.file.InvalidPathException;
import java.nio.file.LinkOption;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.BasicFileAttributes;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.locks.ReentrantLock;

import com.codepilot1c.core.filesystem.SecureDirectoryCapabilityException;
import com.codepilot1c.core.filesystem.SecureDirectoryMutation;
import com.codepilot1c.core.filesystem.SecureDirectoryMutation.BoundRoot;
import com.codepilot1c.core.filesystem.SecureDirectoryMutation.CapabilityPolicy;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonSyntaxException;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonToken;
import com.google.gson.stream.JsonWriter;

/**
 * Persists {@link GsdState} under {@code <project>/.codepilot1c/gsd}.
 *
 * <p>{@code state.json} is the single source of truth. {@code STATE.md} and {@code PLAN.md}
 * are deterministic projections regenerated by this store from JSON and carry no
 * independent state. Writes are atomic: a temp file is written in the GSD directory,
 * {@link FileChannel#force(boolean) force}d to disk, and moved into place with
 * a same-directory rename through an open, validated {@link java.nio.file.SecureDirectoryStream}
 * handle. Java 17 providers without that API fail closed before the first mutation; pathname
 * validation is not treated as a substitute for a stable relative handle.</p>
 *
 * <p>Optimistic concurrency is enforced via the cycle/generation/revision
 * {@link GsdConcurrencyToken} <b>under a cross-process
 * {@link FileLock}</b> on {@code .codepilot1c/gsd/state.lock}: {@link #save(GsdState)}
 * acquires the lock, checks that {@code state.revision()} equals the revision on disk,
 * backs up the previous {@code state.json} to {@code state.json.bak}, persists the new
 * state with {@code revision + 1}, regenerates projections, and releases the lock — all
 * as one critical section, so two writers cannot both pass the CAS. Within a single
 * JVM the OS {@link FileLock} is owned by the process; a second channel on the same
 * lock file throws {@link OverlappingFileLockException} instead of blocking, so the
 * store additionally serializes threads with a per-directory-identity {@link
 * java.util.concurrent.locks.ReentrantLock}. Across processes, only the OS file lock
 * serializes writers. A revision mismatch raises {@link GsdStaleRevisionException}
 * (fail-closed) so the caller reloads and retries. Backup recovery advances generation,
 * and a new delivery cycle changes cycle id, so revision reuse cannot cause ABA.</p>
 *
 * <p>Backup/recovery: on {@link #load()}, a primary {@code state.json} that is
 * {@link GsdCorruptException corrupt} is recovered from {@code state.json.bak} (the
 * corrupt file is quarantined to {@code state.json.corrupt} for forensics; quarantine
 * failures propagate). A <em>missing</em> primary with a <em>valid</em> backup is also
 * recovered. Ordinary access/I/O failures (e.g. {@link AccessDeniedException}) propagate
 * verbatim — they are never treated as corruption and never trigger silent backup
 * recovery. If the primary is corrupt and the backup is missing or corrupt, the store
 * fails closed with {@link GsdCorruptException}. A genuinely fresh project (no
 * {@code state.json}, no {@code .bak}) yields a fresh {@link GsdState#fresh()} without
 * writing a primary state file; missing Markdown projections may still be generated.</p>
 *
 * <p>The {@link GsdGuard} invariants are validated before any write, so a state that would
 * close work on {@link GsdProvenance#INFERRED}-only evidence can never reach disk.</p>
 *
 * <p>Filesystem confinement: the GSD directory is resolved under the supplied project
 * root and must stay inside it after symlink resolution; escapes are rejected. This is
 * pure core, provider-neutral, with no UI dependencies.</p>
 *
 * <h2>Directory fsync limitation</h2>
 * <p>{@link java.nio.file.SecureDirectoryStream} does not expose an anchored directory-fsync
 * operation. Opening the directory again by pathname would reintroduce the ancestry race this
 * class prevents, so it is intentionally not attempted. The temp file itself is forced before the
 * same-directory atomic rename. After an OS crash, rename durability remains filesystem-dependent;
 * the backup and recovery path can restore the prior revision.</p>
 */
public final class GsdStateStore {

    private static final System.Logger LOGGER =
            System.getLogger(GsdStateStore.class.getName());

    /** Directory under the project root where GSD state lives. */
    public static final String GSD_DIR_NAME = ".codepilot1c/gsd"; //$NON-NLS-1$
    /** Primary state file (source of truth). */
    public static final String STATE_JSON = "state.json"; //$NON-NLS-1$
    /** Backup of the previous good state. */
    public static final String STATE_BAK = "state.json.bak"; //$NON-NLS-1$
    /** Forensic copy of a corrupt state.json. */
    public static final String STATE_CORRUPT = "state.json.corrupt"; //$NON-NLS-1$
    /** Cross-process inter-process lock file. */
    public static final String STATE_LOCK = "state.lock"; //$NON-NLS-1$

    /** Hard ceiling for the portable read-only state path. */
    static final long MAX_READ_ONLY_STATE_BYTES = 16L * 1024L * 1024L;

    /**
     * Per-directory-identity JVM mutexes. {@link FileLock} is held by the JVM as a whole: a second
     * {@link FileChannel} on the same path in the same process does <em>not</em> block on
     * {@link FileChannel#lock()} — it throws {@link OverlappingFileLockException} because
     * the JVM already owns the lock region. To serialize threads within a single JVM
     * while still using an OS {@link FileLock} to serialize across processes, each store
     * first acquires a {@link ReentrantLock} keyed by the stable identity of the GSD directory, then
     * acquires the OS file lock. The map is static so all store instances in this JVM
     * share the same per-path mutex.
     */
    private static final ConcurrentHashMap<Object, ReentrantLock> JVM_LOCKS =
            new ConcurrentHashMap<>();

    private final Path projectRoot;
    private final Path gsdDir;
    private final Path statePath;
    private final Path bakPath;
    private final Gson gson;
    private final BoundRoot boundProjectRoot;
    private final SecureDirectoryMutation.MutationHook mutationHook;

    /**
     * Creates a store confined to {@code <projectRoot>/.codepilot1c/gsd}.
     *
     * @param projectRoot the project root (must not be {@code null})
     * @throws IOException if the project root is invalid or confinement cannot be established
     */
    public GsdStateStore(Path projectRoot) throws IOException {
        this(projectRoot, null);
    }

    GsdStateStore(Path projectRoot, SecureDirectoryMutation.MutationHook mutationHook)
            throws IOException {
        this(projectRoot, mutationHook, CapabilityPolicy.REQUIRE_SECURE);
    }

    GsdStateStore(Path projectRoot, SecureDirectoryMutation.MutationHook mutationHook,
            CapabilityPolicy capabilityPolicy) throws IOException {
        this.projectRoot = normalizeRoot(projectRoot);
        Path candidate = this.projectRoot.resolve(GSD_DIR_NAME).toAbsolutePath().normalize();
        if (!candidate.startsWith(this.projectRoot)) {
            throw new AccessDeniedException(candidate.toString(), null,
                    "GSD path escapes project root"); //$NON-NLS-1$
        }
        this.gsdDir = candidate;
        this.statePath = gsdDir.resolve(STATE_JSON);
        this.bakPath = gsdDir.resolve(STATE_BAK);
        this.gson = buildGson();
        Objects.requireNonNull(capabilityPolicy, "capabilityPolicy"); //$NON-NLS-1$
        this.boundProjectRoot = SecureDirectoryMutation.bindRoot(
                this.projectRoot, capabilityPolicy);
        this.mutationHook = mutationHook;
    }

    /**
     * Convenience constructor accepting a string project root path.
     *
     * @param projectRootPath the project root path
     * @throws IOException if the path is invalid or confinement cannot be established
     */
    public GsdStateStore(String projectRootPath) throws IOException {
        this(parseRoot(projectRootPath));
    }

    /**
     * @return the confined GSD directory (must be pre-created before mutation)
     */
    public Path getGsdDirectory() {
        return gsdDir;
    }

    /**
     * @return the project root this store is confined to
     */
    public Path getProjectRoot() {
        return projectRoot;
    }

    /**
     * Loads the current state under the cross-process lock. Returns
     * {@link GsdState#fresh()} for a pre-provisioned GSD directory with no state yet.
     * Recovers from {@code state.json.bak} if {@code state.json} is corrupt or missing,
     * restoring the recovered state to {@code state.json} and regenerating projections.
     * The {@code .codepilot1c/gsd} directory must already exist because Java 17 has no portable
     * secure relative directory-creation primitive. Fails closed with
     * {@link GsdCorruptException} if the primary is corrupt and the
     * backup is missing or corrupt. Ordinary I/O failures propagate as
     * {@link IOException}.
     *
     * @return the loaded (or fresh) state, never {@code null}
     * @throws IOException            if the state is corrupt and unrecoverable, or I/O fails
     */
    public GsdState load() throws IOException {
        ensureConfined();
        return withLock(directory -> {
            ReadOutcome outcome = readOutcome(directory);
            if (outcome.state == null) {
                // Fresh project: nothing on disk.
                GsdState fresh = GsdState.fresh();
                regenerateProjectionsIfMissing(directory, fresh);
                return fresh;
            }
            if (outcome.recovered) {
                if (outcome.primaryWasCorrupt) {
                    quarantineCorruptPrimary(directory); // propagates IOException on failure
                }
                GsdState recovered = outcome.state.recovered();
                atomicWrite(directory, STATE_JSON, toBytes(recovered), Mutation.STATE);
                // Advance the recovery fence in both copies. Repeated recovery without
                // an intervening save must still produce a new generation.
                atomicWrite(directory, STATE_BAK, toBytes(recovered), Mutation.BACKUP);
                writeProjectionsUnlocked(directory, recovered);
                return recovered;
            } else if (outcome.migrated) {
                // Preserve the original v1 payload as the backup, then publish v2.
                atomicWrite(directory, STATE_BAK, directory.readAllBytes(STATE_JSON), Mutation.BACKUP);
                atomicWrite(directory, STATE_JSON, toBytes(outcome.state), Mutation.STATE);
                writeProjectionsUnlocked(directory, outcome.state);
            } else {
                regenerateProjectionsIfMissing(directory, outcome.state);
            }
            return outcome.state;
        });
    }

    /**
     * Reads the current state without any filesystem writes.
     *
     * <p>Unlike {@link #load()}, this method never creates directories, never acquires
     * the cross-process lock, never regenerates projections, never quarantines or
     * publishes a backup, and never recovers from {@code state.json.bak}. Because
     * writes are atomic ({@link java.nio.file.StandardCopyOption#ATOMIC_MOVE}), a concurrent
     * reader is safe: it either sees the fully-written previous state or the new one,
     * never a half-written file.</p>
     *
     * <p>Behavior:</p>
     * <ul>
     *   <li>Primary {@code state.json} exists and parses correctly → returns the parsed state.</li>
     *   <li>Primary {@code state.json} exists but is corrupt → throws
     *       {@link GsdCorruptException} (caller surfaces the error in the UI).</li>
     *   <li>Primary {@code state.json} does not exist → returns {@link GsdState#fresh()}.</li>
     *   <li>I/O failure reading the primary → propagates as {@link IOException}.</li>
     * </ul>
     *
     * <p>This is the deliberately separate portable read path. It does not require
     * {@link java.nio.file.SecureDirectoryStream}: every existing component below the
     * bound project root is checked with {@link LinkOption#NOFOLLOW_LINKS}, symbolic-link
     * traversal is rejected, lexical and real ancestry must agree, the final file is
     * opened with {@code NOFOLLOW_LINKS}, and component identity/metadata is revalidated
     * after the bytes are read. These checks are the strongest practical portable Java 17
     * confinement for a strictly non-mutating read. They cannot provide the stable
     * relative handle used by mutation paths, so a detected concurrent pathname change
     * fails closed instead of returning data.</p>
     *
     * <p>This method is designed for read-only UI consumers (e.g. status panels)
     * that must never mutate the project directory.</p>
     *
     * @return the loaded state, or {@link GsdState#fresh()} when no primary exists; never {@code null}
     * @throws GsdCorruptException  if the primary exists but is corrupt
     * @throws GsdUnsupportedSchemaException if the primary uses a newer schema version
     * @throws AccessDeniedException if an existing read path component is a symbolic link,
     *                               escapes the project root, or changes during the read
     * @throws IOException          on I/O failure reading the primary
     */
    public GsdState loadReadOnly() throws IOException {
        PortableReadSnapshot before = capturePortableReadSnapshot();
        if (!before.stateExists()) {
            verifyPortableReadSnapshot(before);
            return GsdState.fresh();
        }
        long expectedSize = before.identities().get(before.identities().size() - 1).size();
        requirePortableReadSize(expectedSize);

        byte[] bytes;
        try (SeekableByteChannel channel = Files.newByteChannel(statePath,
                java.util.Set.of(StandardOpenOption.READ, LinkOption.NOFOLLOW_LINKS));
                ByteArrayOutputStream output = new ByteArrayOutputStream((int) expectedSize)) {
            ByteBuffer buffer = ByteBuffer.allocate(8192);
            long total = 0L;
            while (true) {
                int read = channel.read(buffer);
                if (read < 0) {
                    break;
                }
                if (read == 0) {
                    continue;
                }
                total += read;
                requirePortableReadSize(total);
                output.write(buffer.array(), 0, read);
                buffer.clear();
            }
            bytes = output.toByteArray();
        }
        if (mutationHook != null) {
            mutationHook.beforeMutation("gsd-read-before-revalidation"); //$NON-NLS-1$
        }
        verifyPortableReadSnapshot(before);
        return parseState(bytes, statePath).state;
    }

    private static void requirePortableReadSize(long size) throws GsdCorruptException {
        if (size < 0L || size > MAX_READ_ONLY_STATE_BYTES) {
            throw new GsdCorruptException("GSD state exceeds the portable read-only limit of " //$NON-NLS-1$
                    + MAX_READ_ONLY_STATE_BYTES + " bytes"); //$NON-NLS-1$
        }
    }

    /**
     * Persists the state atomically under the cross-process lock. Enforces
     * {@link GsdGuard} and optimistic revision before writing. Backs up the previous
     * {@code state.json} to {@code state.json.bak}, writes the new state with
     * {@code revision + 1}, and attempts to regenerate {@code STATE.md}/{@code PLAN.md}.
     * Use {@link #commit(GsdState)} when projection warnings must be observed.
     *
     * @param state the state to persist; its full {@link GsdState#concurrencyToken()} is checked
     * @return the newly persisted state with incremented revision (never {@code null})
     * @throws GsdGuardException          if the state violates invariants
     * @throws GsdStaleRevisionException if {@code state.revision()} does not match disk
     * @throws IOException               on I/O failure or unrecoverable corruption (fail-closed)
     */
    public GsdState save(GsdState state) throws IOException {
        GsdCommitOutcome outcome = commit(state);
        logProjectionWarnings("save", outcome); //$NON-NLS-1$
        return outcome.state();
    }

    /**
     * Atomically commits authoritative state and reports non-authoritative projection
     * failures as warnings. If this method returns, {@code committed()} is true.
     * Failures before the state rename still throw and commit nothing.
     *
     * @param state desired state carrying the expected concurrency token
     * @return committed state plus projection warnings
     * @throws IOException on authoritative persistence failure
     */
    public GsdCommitOutcome commit(GsdState state) throws IOException {
        GsdState validated = Objects.requireNonNull(state, "state"); //$NON-NLS-1$
        GsdGuard.validate(validated); // fail-closed before any write / before the lock

        return withLock(directory -> {
            validateBeforeSave(directory, validated);
            GsdState next = validated.withRevision(validated.revision() + 1L);
            commitAuthoritative(directory, next);
            return projectionOutcome(directory, next);
        });
    }

    /** Compatibility alias emphasizing that projection warnings are returned. */
    public GsdCommitOutcome saveWithOutcome(GsdState state) throws IOException {
        return commit(state);
    }

    /**
     * Commits a CLOSED-to-DISCOVERY cycle replacement against the old token. The new
     * cycle starts at revision zero, so the explicit expected token is required.
     */
    public GsdCommitOutcome commitNewCycle(GsdConcurrencyToken expectedToken,
            GsdState newCycle) throws IOException {
        Objects.requireNonNull(expectedToken, "expectedToken"); //$NON-NLS-1$
        GsdState validated = Objects.requireNonNull(newCycle, "newCycle"); //$NON-NLS-1$
        return withLock(directory -> {
            ReadOutcome outcome = readOutcome(directory);
            if (outcome.state == null || outcome.recovered || outcome.migrated) {
                throw new GsdCorruptException(
                        "cannot replace cycle until primary state is loaded and current"); //$NON-NLS-1$
            }
            if (!expectedToken.equals(outcome.state.concurrencyToken())) {
                throw new GsdStaleTokenException(expectedToken, outcome.state.concurrencyToken());
            }
            // Identity checks intentionally precede aggregate validation so cycle reuse
            // and generation regression produce their explicit errors rather than an
            // incidental transition-revision monotonicity violation.
            GsdCycleRules.validateReplacement(outcome.state, validated);
            GsdGuard.validate(validated);
            commitAuthoritative(directory, validated);
            return projectionOutcome(directory, validated);
        });
    }

    private static void logProjectionWarnings(String operation, GsdCommitOutcome outcome) {
        for (String warning : outcome.projectionWarnings()) {
            LOGGER.log(System.Logger.Level.WARNING,
                    "GSD {0} committed {1} with projection warning: {2}", //$NON-NLS-1$
                    operation, outcome.state().concurrencyToken(), warning);
        }
    }

    private void commitAuthoritative(SecureDirectoryMutation directory, GsdState next)
            throws IOException {
        if (directory.exists(STATE_JSON)) {
            atomicWrite(directory, STATE_BAK, directory.readAllBytes(STATE_JSON), Mutation.BACKUP);
        }
        atomicWrite(directory, STATE_JSON, toBytes(next), Mutation.STATE);
    }

    private GsdCommitOutcome projectionOutcome(SecureDirectoryMutation directory, GsdState next) {
        List<String> warnings = new ArrayList<>();
        try {
            writeProjectionsUnlocked(directory, next);
        } catch (IOException | RuntimeException e) {
            warnings.add("state committed but projections were not fully regenerated: " //$NON-NLS-1$
                    + e.getClass().getSimpleName() + ": " + e.getMessage()); //$NON-NLS-1$
        }
        return new GsdCommitOutcome(next, true, warnings);
    }

    /**
     * Pre-save validation under lock. Returns the state found on disk (for revision
     * comparison and stale-revision checks). Handles three cases:
     * <ul>
     *   <li>Fresh project ({@code state==null}): returns {@code null} to signal
     *       no prior state exists.</li>
     *   <li>Recovery needed ({@code recovered==true}): fails closed with
     *       {@link GsdCorruptException} because only a validated primary may be backed up.</li>
     *   <li>Normal state on disk: returns the valid state for CAS checking.</li>
     * </ul>
     */
    private void validateBeforeSave(SecureDirectoryMutation directory, GsdState validated)
            throws IOException {
        ReadOutcome outcome = readOutcome(directory);

        // Fresh project: no existing state on disk, nothing to back up.
        if (outcome.state == null) {
            if (validated.revision() != GsdState.INITIAL_REVISION) {
                throw new GsdStaleRevisionException(
                        validated.revision(), GsdState.INITIAL_REVISION);
            }
            return;
        }

        // If the store had to recover (primary was corrupt or missing),
        // reject the save: only a validated primary may be backed up. A recovered state
        // is transient — the caller must reload via load() to obtain a clean snapshot
        // before attempting another save.
        if (outcome.recovered || outcome.migrated) {
            throw new GsdCorruptException(
                    "GSD primary requires recovery or migration; save rejected until load() completes"); //$NON-NLS-1$
        }

        // Compare the complete identity; revision-only comparison permits ABA after
        // recovery or cycle replacement.
        if (!validated.concurrencyToken().equals(outcome.state.concurrencyToken())) {
            throw new GsdStaleTokenException(
                    validated.concurrencyToken(), outcome.state.concurrencyToken());
        }
        // The used-cycle fence is authoritative ABA protection. Ordinary commits
        // must preserve it exactly; commitNewCycle is the only path allowed to append.
        if (!validated.usedCycleIds().equals(outcome.state.usedCycleIds())) {
            throw new IllegalArgumentException(
                    "ordinary commit must preserve the used-cycle identity fence"); //$NON-NLS-1$
        }
    }

    /**
     * Regenerates the {@code STATE.md} and {@code PLAN.md} projections from the given
     * state under the cross-process lock, without changing {@code state.json}. Useful
     * after a fresh checkout or manual edits.
     *
     * @param state the state to project
     * @throws IOException on I/O failure
     */
    public void writeProjections(GsdState state) throws IOException {
        Objects.requireNonNull(state, "state"); //$NON-NLS-1$
        withLock(directory -> {
            writeProjectionsUnlocked(directory, state);
            return null;
        });
    }

    // ---- Internals -------------------------------------------------------

    private void writeProjectionsUnlocked(SecureDirectoryMutation directory, GsdState state)
            throws IOException {
        atomicWriteText(directory, GsdProjections.STATE_FILE,
                GsdProjections.toStateMd(state), Mutation.PROJECTION);
        atomicWriteText(directory, GsdProjections.PLAN_FILE,
                GsdProjections.toPlanMd(state), Mutation.PROJECTION);
    }

    /**
     * Executes {@code action} while holding an exclusive cross-process {@link FileLock}
     * on {@code state.lock}. The lock file is created on demand. Because {@link FileLock}
     * is owned by the JVM (not the channel), a second channel in the same JVM throws
     * {@link OverlappingFileLockException}; to serialize threads within the process we
     * first take a {@link ReentrantLock} keyed by the GSD directory's stable identity, then take the
     * OS file lock. Across processes, only the OS {@link FileLock} serializes writers.
     */
    private <T> T withLock(IoAction<T> action) throws IOException {
        ensureConfined();
        // Capability comes first: precreating directories cannot remedy a provider
        // that has no SecureDirectoryStream (including the macOS Java 17 provider).
        SecureDirectoryMutation.requireSecureDirectoryStreams(boundProjectRoot);
        if (!Files.isDirectory(gsdDir, java.nio.file.LinkOption.NOFOLLOW_LINKS)) {
            if (mutationHook != null) {
                mutationHook.beforeMutation("gsd-directory-create"); //$NON-NLS-1$
            }
            throw new SecureDirectoryCapabilityException(gsdDir,
                    "secure GSD directory creation is unavailable on Java 17; " //$NON-NLS-1$
                            + "pre-create .codepilot1c/gsd inside the project"); //$NON-NLS-1$
        }
        try (SecureDirectoryMutation directory = SecureDirectoryMutation.open(
                boundProjectRoot, gsdDir, mutationHook, "gsd-directory-bind")) { //$NON-NLS-1$
            Object lockIdentity = directory.identityKey();
            ReentrantLock jvmLock = JVM_LOCKS.computeIfAbsent(
                    lockIdentity, k -> new ReentrantLock());
            jvmLock.lock();
            try {
                FileChannel channel = directory.openFileChannel(STATE_LOCK,
                        java.util.Set.of(StandardOpenOption.WRITE, StandardOpenOption.CREATE),
                        Mutation.LOCK.operation);
                try {
                    FileLock lock;
                    try {
                        lock = channel.lock();
                    } catch (OverlappingFileLockException e) {
                        // Should not happen: the JVM lock guarantees a single in-process holder.
                        throw new IOException("GSD lock is already held in this JVM", e); //$NON-NLS-1$
                    }
                    try {
                        directory.validateCurrent();
                        return action.run(directory);
                    } finally {
                        releaseQuietly(lock);
                    }
                } finally {
                    closeQuietly(channel);
                }
            } finally {
                jvmLock.unlock();
            }
        }
    }

    @FunctionalInterface
    private interface IoAction<T> {
        T run(SecureDirectoryMutation directory) throws IOException;
    }

    private void regenerateProjectionsIfMissing(
            SecureDirectoryMutation directory, GsdState state) throws IOException {
        if (!directory.exists(GsdProjections.STATE_FILE)
                || !directory.exists(GsdProjections.PLAN_FILE)) {
            writeProjectionsUnlocked(directory, state);
        }
    }

    /**
     * Reads the primary state file, falling back to the backup if the primary is
     * {@link GsdCorruptException corrupt} (parse/schema error only) or missing while a
     * valid backup exists. Ordinary access/I/O failures propagate verbatim.
     */
    private ReadOutcome readOutcome(SecureDirectoryMutation directory) throws IOException {
        boolean primaryCorrupt = false;
        if (directory.exists(STATE_JSON)) {
            try {
                ParsedState parsed = parseState(
                        directory.readAllBytes(STATE_JSON), statePath);
                return new ReadOutcome(parsed.state, false, false, parsed.migrated);
            } catch (GsdCorruptException e) {
                primaryCorrupt = true;
            }
        }
        if (directory.exists(STATE_BAK)) {
            try {
                ParsedState parsed = parseState(
                        directory.readAllBytes(STATE_BAK), bakPath);
                return new ReadOutcome(parsed.state, primaryCorrupt, true, parsed.migrated);
            } catch (GsdCorruptException e) {
                // backup also corrupt
                if (primaryCorrupt) {
                    throw new GsdCorruptException("GSD " + STATE_JSON //$NON-NLS-1$
                            + " and " + STATE_BAK + " are both corrupt", e); //$NON-NLS-1$ //$NON-NLS-2$
                }
                // primary missing, backup corrupt -> fail closed on the backup.
                throw new GsdCorruptException("GSD " + STATE_BAK + " is corrupt and " //$NON-NLS-1$ //$NON-NLS-2$
                        + STATE_JSON + " is missing: " + e.getMessage(), e); //$NON-NLS-1$ //$NON-NLS-2$
            }
        }
        if (primaryCorrupt) {
            throw new GsdCorruptException("GSD " + STATE_JSON + " is corrupt and " //$NON-NLS-1$ //$NON-NLS-2$
                    + STATE_BAK + " is missing"); //$NON-NLS-1$
        }
        // primary simply missing and no backup to recover from (fresh project).
        return new ReadOutcome(null, false, false, false);
    }

    /**
     * Moves the corrupt primary {@code state.json} to {@code state.json.corrupt} for
     * forensic analysis. Fails closed by propagating any {@link IOException}; the
     * original recovery is abandoned so a corrupt file is never silently lost.
     */
    private void quarantineCorruptPrimary(SecureDirectoryMutation directory) throws IOException {
        if (!directory.exists(STATE_JSON)) {
            return;
        }
        directory.move(STATE_JSON, STATE_CORRUPT, Mutation.QUARANTINE.operation);
        // If a previous forensic copy lingered, only one .corrupt is kept (REPLACE_EXISTING).
    }

    private byte[] toBytes(GsdState state) {
        return gson.toJson(state).getBytes(StandardCharsets.UTF_8);
    }

    /**
     * Parses {@code path} as a {@link GsdState}. Raises {@link GsdCorruptException} for
     * unparseable JSON, a JSON {@code null} document, an empty document, a
     * unsupported historical schema, or a {@link GsdGuard} invariant violation. Schema v1
     * is migrated explicitly; a future schema raises {@link GsdUnsupportedSchemaException}.
     * All other
     * {@link IOException}s propagate.
     */
    private ParsedState parseState(Path path) throws IOException {
        long size;
        try {
            size = Files.size(path);
        } catch (IOException e) {
            throw e; // access failure propagates verbatim
        }
        if (size == 0) {
            throw new GsdCorruptException("empty GSD state file: " + path); //$NON-NLS-1$
        }
        try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
            return parseState(reader, path);
        }
    }

    private ParsedState parseState(byte[] bytes, Path displayPath) throws IOException {
        if (bytes.length == 0) {
            throw new GsdCorruptException("empty GSD state file: " + displayPath); //$NON-NLS-1$
        }
        try (Reader reader = new InputStreamReader(
                new ByteArrayInputStream(bytes), StandardCharsets.UTF_8)) {
            return parseState(reader, displayPath);
        }
    }

    private ParsedState parseState(Reader reader, Path path) throws IOException {
        JsonObject document;
        try {
            JsonElement parsed = JsonParser.parseReader(reader);
            if (parsed == null || parsed.isJsonNull()) {
                throw new GsdCorruptException("GSD state file is JSON null: " + path); //$NON-NLS-1$
            }
            if (!parsed.isJsonObject()) {
                throw new GsdCorruptException("GSD state file is not a JSON object: " + path); //$NON-NLS-1$
            }
            document = parsed.getAsJsonObject();
        } catch (JsonSyntaxException e) {
            throw new GsdCorruptException("invalid JSON in " + path + ": " + e.getMessage(), e); //$NON-NLS-1$ //$NON-NLS-2$
        }
        JsonElement schemaElement = document.get("schemaVersion"); //$NON-NLS-1$
        if (schemaElement == null || !schemaElement.isJsonPrimitive()
                || !schemaElement.getAsJsonPrimitive().isNumber()) {
            throw new GsdCorruptException("missing or invalid GSD schemaVersion in " + path); //$NON-NLS-1$
        }
        int schemaVersion;
        try {
            schemaVersion = Integer.parseInt(schemaElement.getAsString());
        } catch (RuntimeException e) {
            throw new GsdCorruptException("invalid GSD schemaVersion in " + path, e); //$NON-NLS-1$
        }
        if (schemaVersion > GsdState.CURRENT_SCHEMA_VERSION) {
            // A future schema is not corruption and must never silently fall back to
            // an older backup.
            throw new GsdUnsupportedSchemaException(schemaVersion);
        }

        final GsdState state;
        final boolean migrated;
        try {
            if (schemaVersion == GsdState.LEGACY_SCHEMA_VERSION) {
                LegacyStateV1 legacy = gson.fromJson(document, LegacyStateV1.class);
                state = GsdState.migratedFromV1(legacy.revision, legacy.phase, legacy.goal,
                        legacy.decisions, legacy.tasks, legacy.waves, legacy.evidence,
                        legacy.sessionPointer);
                migrated = true;
            } else if (schemaVersion == GsdState.CURRENT_SCHEMA_VERSION) {
                state = gson.fromJson(document, GsdState.class);
                migrated = false;
            } else {
                throw new GsdCorruptException("unsupported historical GSD schemaVersion " //$NON-NLS-1$
                        + schemaVersion + " in " + path); //$NON-NLS-1$
            }
        } catch (RuntimeException e) {
            throw new GsdCorruptException("invalid GSD state in " + path + ": " //$NON-NLS-1$ //$NON-NLS-2$
                    + e.getMessage(), e);
        }
        // Guard validation: a deserialized state that violates invariants is treated as
        // corruption so that backup-recovery paths never republish invalid state.
        try {
            GsdGuard.validate(state);
        } catch (GsdGuardException e) {
            throw new GsdCorruptException("GSD state in " + path + " fails guard validation: " //$NON-NLS-1$ //$NON-NLS-2$
                    + e.getMessage(), e);
        }
        return new ParsedState(state, migrated);
    }

    /**
     * Writes {@code bytes} to {@code target} via a temp file in the same directory,
     * {@link FileChannel#force force}d to disk, then moved into place atomically. The
     * full payload is written in a loop so short writes cannot leave a partial file.
     * Publication is through the already-open directory handle, so pathname ancestry replacement
     * cannot redirect the rename. Providers without secure relative handles fail before this
     * method can create a temp file.
     */
    private void atomicWrite(SecureDirectoryMutation directory, String target,
            byte[] bytes, Mutation mutation) throws IOException {
        directory.atomicWrite(target, bytes, mutation.operation);
    }

    private void atomicWriteText(SecureDirectoryMutation directory, String target,
            String text, Mutation mutation) throws IOException {
        atomicWrite(directory, target, text.getBytes(StandardCharsets.UTF_8), mutation);
    }

    enum Mutation {
        LOCK("gsd-lock"), //$NON-NLS-1$
        STATE("gsd-state"), //$NON-NLS-1$
        BACKUP("gsd-backup"), //$NON-NLS-1$
        PROJECTION("gsd-projection"), //$NON-NLS-1$
        QUARANTINE("gsd-quarantine"); //$NON-NLS-1$

        private final String operation;

        Mutation(String operation) {
            this.operation = operation;
        }

        String operation() {
            return operation;
        }
    }

    private static void closeQuietly(FileChannel channel) {
        try {
            channel.close();
        } catch (IOException ignored) {
            // closing the lock channel also releases the lock
        }
    }

    private static void releaseQuietly(FileLock lock) {
        try {
            lock.release();
        } catch (IOException ignored) {
            // best-effort release; channel close will also release
        }
    }

    private static Path normalizeRoot(Path root) throws IOException {
        if (root == null) {
            throw new IOException("project root must not be null"); //$NON-NLS-1$
        }
        try {
            return root.toAbsolutePath().normalize();
        } catch (InvalidPathException e) {
            throw new IOException("invalid project root: " + root, e); //$NON-NLS-1$
        }
    }

    private static Path parseRoot(String path) throws IOException {
        if (path == null || path.isBlank()) {
            throw new IOException("project root path must not be blank"); //$NON-NLS-1$
        }
        try {
            return Path.of(path);
        } catch (InvalidPathException e) {
            throw new IOException("invalid project root path: " + path, e); //$NON-NLS-1$
        }
    }

    /** Captures a portable, strictly read-only view of the GSD state path. */
    private PortableReadSnapshot capturePortableReadSnapshot() throws IOException {
        boundProjectRoot.verifyCurrent();
        Path realRoot = projectRoot.toRealPath();
        if (!statePath.startsWith(projectRoot) || statePath.equals(projectRoot)) {
            throw deniedRead(statePath, "GSD state path escapes the project root"); //$NON-NLS-1$
        }

        List<PortablePathIdentity> identities = new ArrayList<>();
        Path current = projectRoot;
        Path relative = projectRoot.relativize(statePath);
        for (int i = 0; i < relative.getNameCount(); i++) {
            current = current.resolve(relative.getName(i));
            boolean finalComponent = i == relative.getNameCount() - 1;
            BasicFileAttributes attributes;
            try {
                attributes = Files.readAttributes(
                        current, BasicFileAttributes.class, LinkOption.NOFOLLOW_LINKS);
            } catch (NoSuchFileException e) {
                return new PortableReadSnapshot(realRoot, List.copyOf(identities),
                        current, false);
            }
            if (attributes.isSymbolicLink()) {
                throw deniedRead(current, "symbolic links are not allowed in the GSD read path"); //$NON-NLS-1$
            }
            if (finalComponent) {
                if (!attributes.isRegularFile()) {
                    throw deniedRead(current, "GSD state is not a regular file"); //$NON-NLS-1$
                }
            } else if (!attributes.isDirectory()) {
                throw deniedRead(current, "GSD read path component is not a directory"); //$NON-NLS-1$
            }

            Path real = current.toRealPath();
            Path expectedReal = realRoot.resolve(projectRoot.relativize(current)).normalize();
            if (!real.startsWith(realRoot) || !real.equals(expectedReal)) {
                throw deniedRead(current,
                        "GSD read path does not preserve real project ancestry"); //$NON-NLS-1$
            }
            identities.add(new PortablePathIdentity(current, real, attributes.fileKey(),
                    attributes.isDirectory(), attributes.size(),
                    attributes.lastModifiedTime().toMillis()));
        }
        return new PortableReadSnapshot(realRoot, List.copyOf(identities), null, true);
    }

    /** Revalidates the complete portable read path after absence detection or byte reading. */
    private void verifyPortableReadSnapshot(PortableReadSnapshot snapshot) throws IOException {
        boundProjectRoot.verifyCurrent();
        if (!projectRoot.toRealPath().equals(snapshot.realRoot())) {
            throw deniedRead(projectRoot, "project root changed during GSD read"); //$NON-NLS-1$
        }
        for (PortablePathIdentity identity : snapshot.identities()) {
            BasicFileAttributes attributes;
            try {
                attributes = Files.readAttributes(identity.path(), BasicFileAttributes.class,
                        LinkOption.NOFOLLOW_LINKS);
            } catch (NoSuchFileException e) {
                throw deniedRead(identity.path(), "GSD read path changed during read"); //$NON-NLS-1$
            }
            Path real = identity.path().toRealPath();
            Object currentKey = attributes.fileKey();
            boolean keyChanged = identity.fileKey() != null && currentKey != null
                    && !identity.fileKey().equals(currentKey);
            if (attributes.isSymbolicLink()
                    || attributes.isDirectory() != identity.directory()
                    || keyChanged
                    || !real.equals(identity.realPath())
                    || attributes.size() != identity.size()
                    || attributes.lastModifiedTime().toMillis() != identity.lastModifiedMillis()) {
                throw deniedRead(identity.path(), "GSD read path changed during read"); //$NON-NLS-1$
            }
        }
        if (!snapshot.stateExists()) {
            try {
                Files.readAttributes(snapshot.firstMissingPath(), BasicFileAttributes.class,
                        LinkOption.NOFOLLOW_LINKS);
                throw deniedRead(snapshot.firstMissingPath(),
                        "GSD read path appeared during read"); //$NON-NLS-1$
            } catch (NoSuchFileException expected) {
                // Stable absence: returning a fresh state is safe and performs no mutation.
            }
        }
    }

    private static AccessDeniedException deniedRead(Path path, String reason) {
        return new AccessDeniedException(path.toString(), null, reason);
    }

    /**
     * Verifies the GSD directory stays inside the project root after symlink resolution,
     * resolving through the longest existing ancestor so a pre-existing symlink (e.g.
     * {@code .codepilot1c} pointing outside the project) is rejected before any directory
     * is created. Called before reads and writes.
     */
    private void ensureConfined() throws IOException {
        Path realRoot;
        try {
            realRoot = projectRoot.toRealPath();
        } catch (IOException e) {
            throw new IOException("project root does not exist or is inaccessible: " //$NON-NLS-1$
                    + projectRoot, e);
        }
        Path existingAncestor = longestExistingAncestor(gsdDir);
        if (existingAncestor == null) {
            return; // no path is dereferenced and mutation will fail closed
        }
        Path realAncestor = existingAncestor.toRealPath();
        if (existingAncestor.getNameCount() < gsdDir.getNameCount()) {
            Path relative = gsdDir.subpath(existingAncestor.getNameCount(), gsdDir.getNameCount());
            Path realGsd = realAncestor.resolve(relative);
            if (!realGsd.startsWith(realRoot)) {
                throw new AccessDeniedException(gsdDir.toString(), null,
                        "GSD directory resolves outside the project root"); //$NON-NLS-1$
            }
        } else if (!realAncestor.startsWith(realRoot)) {
            throw new AccessDeniedException(gsdDir.toString(), null,
                    "GSD directory resolves outside the project root"); //$NON-NLS-1$
        }
    }

    private static Path longestExistingAncestor(Path path) {
        Path cur = path;
        while (cur != null && !Files.exists(cur)) {
            cur = cur.getParent();
        }
        return cur;
    }

    private static Gson buildGson() {
        return new GsonBuilder()
                .setPrettyPrinting()
                .disableHtmlEscaping()
                .registerTypeAdapter(Instant.class, new InstantAdapter().nullSafe())
                .registerTypeAdapter(GsdPhase.class, new EnumStrictAdapter<>(GsdPhase.class, "phase"))
                .registerTypeAdapter(GsdTaskStatus.class, new EnumStrictAdapter<>(GsdTaskStatus.class, "task status"))
                .registerTypeAdapter(GsdProvenance.class, new EnumStrictAdapter<>(GsdProvenance.class, "provenance"))
                .registerTypeAdapter(GsdExecutionKind.class, new EnumStrictAdapter<>(GsdExecutionKind.class, "execution kind"))
                .registerTypeAdapter(GsdAcceptanceStatus.class, new EnumStrictAdapter<>(GsdAcceptanceStatus.class, "acceptance status"))
                .registerTypeAdapter(GsdShipmentStatus.class, new EnumStrictAdapter<>(GsdShipmentStatus.class, "shipment status"))
                .create();
    }

    /** Outcome of a read attempt, tracking whether recovery from backup occurred. */
    private static final class ReadOutcome {
        final GsdState state;
        final boolean primaryWasCorrupt;
        final boolean recovered;
        final boolean migrated;

        ReadOutcome(GsdState state, boolean primaryWasCorrupt, boolean recovered, boolean migrated) {
            this.state = state;
            this.primaryWasCorrupt = primaryWasCorrupt;
            this.recovered = recovered;
            this.migrated = migrated;
        }
    }

    private static final class ParsedState {
        final GsdState state;
        final boolean migrated;

        ParsedState(GsdState state, boolean migrated) {
            this.state = state;
            this.migrated = migrated;
        }
    }

    private record PortableReadSnapshot(
            Path realRoot,
            List<PortablePathIdentity> identities,
            Path firstMissingPath,
            boolean stateExists) {
    }

    private record PortablePathIdentity(
            Path path,
            Path realPath,
            Object fileKey,
            boolean directory,
            long size,
            long lastModifiedMillis) {
    }

    /** Exact schema-v1 shape used only by the explicit one-step migrator. */
    private static final class LegacyStateV1 {
        long revision;
        GsdPhase phase;
        String goal;
        List<GsdDecision> decisions;
        List<GsdTask> tasks;
        List<GsdWave> waves;
        List<GsdEvidence> evidence;
        GsdSessionPointer sessionPointer;
    }

    /**
     * Strict {@link TypeAdapter} for Java enums that treats any unrecognized JSON string
     * as corruption rather than silently falling back to {@code null} or a default value.
     *
     * @param <E> the enum type
     */
    private static final class EnumStrictAdapter<E extends Enum<E>> extends TypeAdapter<E> {
        private final Class<E> enumType;
        private final String fieldName; // for error messages

        EnumStrictAdapter(Class<E> enumType, String fieldName) {
            this.enumType = enumType;
            this.fieldName = fieldName;
        }

        @Override
        public void write(JsonWriter out, E value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(value.name());
            }
        }

        @Override
        public E read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                throw new GsdCorruptException(
                        "Null " + fieldName + " value in JSON — possible data corruption"); //$NON-NLS-1$ //$NON-NLS-2$
            }
            String name = in.nextString();
            try {
                return Enum.valueOf(enumType, name);
            } catch (IllegalArgumentException e) {
                throw new GsdCorruptException("Unknown " + fieldName + " value '" + name
                        + "' in JSON — possible data corruption", e);
            }
        }
    }

    /** ISO-8601 adapter for {@link Instant} so JSON is human-readable and deterministic. */
    private static final class InstantAdapter extends TypeAdapter<Instant> {
        @Override
        public void write(JsonWriter out, Instant value) throws IOException {
            out.value(value.toString());
        }

        @Override
        public Instant read(JsonReader in) throws IOException {
            if (in.peek() == JsonToken.NULL) {
                in.nextNull();
                return null;
            }
            return Instant.parse(in.nextString());
        }
    }
}
