package com.codepilot1c.core.edt.ast;

/**
 * Standardized EDT AST error codes.
 */
public enum EdtAstErrorCode {
    PROJECT_NOT_FOUND,
    PROJECT_NOT_READY,
    FILE_NOT_FOUND,
    INVALID_POSITION,
    EDT_SERVICE_UNAVAILABLE,
    INVALID_ARGUMENT,
    METHOD_NOT_FOUND,
    AMBIGUOUS_METHOD,
    MODULE_PARSE_ERROR,
    INTERNAL_ERROR,
    // Debug-specific error codes
    DEBUG_API_ERROR,
    DEBUG_NO_TARGET,
    DEBUG_BREAKPOINT_NOT_FOUND,
    DEBUG_THREAD_NOT_FOUND,
    DEBUG_EVALUATION_FAILED,
    DEBUG_STEP_FAILED,
    DEBUG_RESUME_FAILED
}
